package com.liang.im.proto;
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageProto.proto

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.Message.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    int getMessageTypeValue();
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.Message.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    MessageProto.Message.MessageType getMessageType();

    /**
     * <code>.Message.Authentication authentication = 2;</code>
     * @return Whether the authentication field is set.
     */
    boolean hasAuthentication();
    /**
     * <code>.Message.Authentication authentication = 2;</code>
     * @return The authentication.
     */
    MessageProto.Message.Authentication getAuthentication();
    /**
     * <code>.Message.Authentication authentication = 2;</code>
     */
    MessageProto.Message.AuthenticationOrBuilder getAuthenticationOrBuilder();

    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     * @return Whether the heartbeat field is set.
     */
    boolean hasHeartbeat();
    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     * @return The heartbeat.
     */
    MessageProto.Message.Heartbeat getHeartbeat();
    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     */
    MessageProto.Message.HeartbeatOrBuilder getHeartbeatOrBuilder();

    public MessageProto.Message.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Message)
      MessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      messageType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 18: {
              MessageProto.Message.Authentication.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((MessageProto.Message.Authentication) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(MessageProto.Message.Authentication.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((MessageProto.Message.Authentication) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              MessageProto.Message.Heartbeat.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((MessageProto.Message.Heartbeat) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(MessageProto.Message.Heartbeat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((MessageProto.Message.Heartbeat) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProto.Message.class, MessageProto.Message.Builder.class);
    }

    /**
     * Protobuf enum {@code Message.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * 认证
       * </pre>
       *
       * <code>AUTHENTICATION = 0;</code>
       */
      AUTHENTICATION(0),
      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEARTBEAT = 1;</code>
       */
      HEARTBEAT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * 认证
       * </pre>
       *
       * <code>AUTHENTICATION = 0;</code>
       */
      public static final int AUTHENTICATION_VALUE = 0;
      /**
       * <pre>
       * 心跳
       * </pre>
       *
       * <code>HEARTBEAT = 1;</code>
       */
      public static final int HEARTBEAT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static MessageType forNumber(int value) {
        switch (value) {
          case 0: return AUTHENTICATION;
          case 1: return HEARTBEAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageProto.Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.MessageType)
    }

    public interface AuthenticationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Message.Authentication)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      java.lang.String getClientId();
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      com.google.protobuf.ByteString
          getClientIdBytes();

      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string clientAddress = 2;</code>
       * @return The clientAddress.
       */
      java.lang.String getClientAddress();
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string clientAddress = 2;</code>
       * @return The bytes for clientAddress.
       */
      com.google.protobuf.ByteString
          getClientAddressBytes();

      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string clientName = 3;</code>
       * @return The clientName.
       */
      java.lang.String getClientName();
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string clientName = 3;</code>
       * @return The bytes for clientName.
       */
      com.google.protobuf.ByteString
          getClientNameBytes();
    }
    /**
     * Protobuf type {@code Message.Authentication}
     */
    public static final class Authentication extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Message.Authentication)
        AuthenticationOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Authentication.newBuilder() to construct.
      private Authentication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Authentication() {
        clientId_ = "";
        clientAddress_ = "";
        clientName_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Authentication();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Authentication(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                clientId_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                clientAddress_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                clientName_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_Authentication_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_Authentication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.Message.Authentication.class, MessageProto.Message.Authentication.Builder.class);
      }

      public static final int CLIENTID_FIELD_NUMBER = 1;
      private volatile java.lang.Object clientId_;
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      @java.lang.Override
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CLIENTADDRESS_FIELD_NUMBER = 2;
      private volatile java.lang.Object clientAddress_;
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string clientAddress = 2;</code>
       * @return The clientAddress.
       */
      @java.lang.Override
      public java.lang.String getClientAddress() {
        java.lang.Object ref = clientAddress_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientAddress_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 地址
       * </pre>
       *
       * <code>string clientAddress = 2;</code>
       * @return The bytes for clientAddress.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClientAddressBytes() {
        java.lang.Object ref = clientAddress_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CLIENTNAME_FIELD_NUMBER = 3;
      private volatile java.lang.Object clientName_;
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string clientName = 3;</code>
       * @return The clientName.
       */
      @java.lang.Override
      public java.lang.String getClientName() {
        java.lang.Object ref = clientName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientName_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 名称
       * </pre>
       *
       * <code>string clientName = 3;</code>
       * @return The bytes for clientName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClientNameBytes() {
        java.lang.Object ref = clientName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientAddress_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientName_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientName_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientAddress_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientAddress_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientName_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientName_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MessageProto.Message.Authentication)) {
          return super.equals(obj);
        }
        MessageProto.Message.Authentication other = (MessageProto.Message.Authentication) obj;

        if (!getClientId()
            .equals(other.getClientId())) return false;
        if (!getClientAddress()
            .equals(other.getClientAddress())) return false;
        if (!getClientName()
            .equals(other.getClientName())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientId().hashCode();
        hash = (37 * hash) + CLIENTADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getClientAddress().hashCode();
        hash = (37 * hash) + CLIENTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getClientName().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MessageProto.Message.Authentication parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Authentication parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Authentication parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Authentication parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Authentication parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Authentication parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Authentication parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Authentication parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageProto.Message.Authentication parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Authentication parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageProto.Message.Authentication parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Authentication parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MessageProto.Message.Authentication prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Message.Authentication}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Message.Authentication)
          MessageProto.Message.AuthenticationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MessageProto.internal_static_Message_Authentication_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MessageProto.internal_static_Message_Authentication_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MessageProto.Message.Authentication.class, MessageProto.Message.Authentication.Builder.class);
        }

        // Construct using MessageProto.Message.Authentication.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          clientId_ = "";

          clientAddress_ = "";

          clientName_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MessageProto.internal_static_Message_Authentication_descriptor;
        }

        @java.lang.Override
        public MessageProto.Message.Authentication getDefaultInstanceForType() {
          return MessageProto.Message.Authentication.getDefaultInstance();
        }

        @java.lang.Override
        public MessageProto.Message.Authentication build() {
          MessageProto.Message.Authentication result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public MessageProto.Message.Authentication buildPartial() {
          MessageProto.Message.Authentication result = new MessageProto.Message.Authentication(this);
          result.clientId_ = clientId_;
          result.clientAddress_ = clientAddress_;
          result.clientName_ = clientName_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MessageProto.Message.Authentication) {
            return mergeFrom((MessageProto.Message.Authentication)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MessageProto.Message.Authentication other) {
          if (other == MessageProto.Message.Authentication.getDefaultInstance()) return this;
          if (!other.getClientId().isEmpty()) {
            clientId_ = other.clientId_;
            onChanged();
          }
          if (!other.getClientAddress().isEmpty()) {
            clientAddress_ = other.clientAddress_;
            onChanged();
          }
          if (!other.getClientName().isEmpty()) {
            clientName_ = other.clientName_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MessageProto.Message.Authentication parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MessageProto.Message.Authentication) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object clientId_ = "";
        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return The clientId.
         */
        public java.lang.String getClientId() {
          java.lang.Object ref = clientId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return The bytes for clientId.
         */
        public com.google.protobuf.ByteString
            getClientIdBytes() {
          java.lang.Object ref = clientId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @param value The clientId to set.
         * @return This builder for chaining.
         */
        public Builder setClientId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearClientId() {
          
          clientId_ = getDefaultInstance().getClientId();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @param value The bytes for clientId to set.
         * @return This builder for chaining.
         */
        public Builder setClientIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientId_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object clientAddress_ = "";
        /**
         * <pre>
         * 地址
         * </pre>
         *
         * <code>string clientAddress = 2;</code>
         * @return The clientAddress.
         */
        public java.lang.String getClientAddress() {
          java.lang.Object ref = clientAddress_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientAddress_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * 地址
         * </pre>
         *
         * <code>string clientAddress = 2;</code>
         * @return The bytes for clientAddress.
         */
        public com.google.protobuf.ByteString
            getClientAddressBytes() {
          java.lang.Object ref = clientAddress_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientAddress_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 地址
         * </pre>
         *
         * <code>string clientAddress = 2;</code>
         * @param value The clientAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientAddress(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientAddress_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 地址
         * </pre>
         *
         * <code>string clientAddress = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearClientAddress() {
          
          clientAddress_ = getDefaultInstance().getClientAddress();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 地址
         * </pre>
         *
         * <code>string clientAddress = 2;</code>
         * @param value The bytes for clientAddress to set.
         * @return This builder for chaining.
         */
        public Builder setClientAddressBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientAddress_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object clientName_ = "";
        /**
         * <pre>
         * 名称
         * </pre>
         *
         * <code>string clientName = 3;</code>
         * @return The clientName.
         */
        public java.lang.String getClientName() {
          java.lang.Object ref = clientName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * 名称
         * </pre>
         *
         * <code>string clientName = 3;</code>
         * @return The bytes for clientName.
         */
        public com.google.protobuf.ByteString
            getClientNameBytes() {
          java.lang.Object ref = clientName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 名称
         * </pre>
         *
         * <code>string clientName = 3;</code>
         * @param value The clientName to set.
         * @return This builder for chaining.
         */
        public Builder setClientName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientName_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 名称
         * </pre>
         *
         * <code>string clientName = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearClientName() {
          
          clientName_ = getDefaultInstance().getClientName();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 名称
         * </pre>
         *
         * <code>string clientName = 3;</code>
         * @param value The bytes for clientName to set.
         * @return This builder for chaining.
         */
        public Builder setClientNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientName_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Message.Authentication)
      }

      // @@protoc_insertion_point(class_scope:Message.Authentication)
      private static final MessageProto.Message.Authentication DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MessageProto.Message.Authentication();
      }

      public static MessageProto.Message.Authentication getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Authentication>
          PARSER = new com.google.protobuf.AbstractParser<Authentication>() {
        @java.lang.Override
        public Authentication parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Authentication(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Authentication> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Authentication> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public MessageProto.Message.Authentication getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface HeartbeatOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Message.Heartbeat)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 客户端id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      java.lang.String getClientId();
      /**
       * <pre>
       * 客户端id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      com.google.protobuf.ByteString
          getClientIdBytes();
    }
    /**
     * Protobuf type {@code Message.Heartbeat}
     */
    public static final class Heartbeat extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Message.Heartbeat)
        HeartbeatOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Heartbeat.newBuilder() to construct.
      private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Heartbeat() {
        clientId_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Heartbeat();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Heartbeat(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                clientId_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_Heartbeat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_Heartbeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.Message.Heartbeat.class, MessageProto.Message.Heartbeat.Builder.class);
      }

      public static final int CLIENTID_FIELD_NUMBER = 1;
      private volatile java.lang.Object clientId_;
      /**
       * <pre>
       * 客户端id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The clientId.
       */
      @java.lang.Override
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 客户端id
       * </pre>
       *
       * <code>string clientId = 1;</code>
       * @return The bytes for clientId.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof MessageProto.Message.Heartbeat)) {
          return super.equals(obj);
        }
        MessageProto.Message.Heartbeat other = (MessageProto.Message.Heartbeat) obj;

        if (!getClientId()
            .equals(other.getClientId())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientId().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static MessageProto.Message.Heartbeat parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Heartbeat parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static MessageProto.Message.Heartbeat parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageProto.Message.Heartbeat parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Heartbeat parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static MessageProto.Message.Heartbeat parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(MessageProto.Message.Heartbeat prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Message.Heartbeat}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Message.Heartbeat)
          MessageProto.Message.HeartbeatOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return MessageProto.internal_static_Message_Heartbeat_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return MessageProto.internal_static_Message_Heartbeat_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  MessageProto.Message.Heartbeat.class, MessageProto.Message.Heartbeat.Builder.class);
        }

        // Construct using MessageProto.Message.Heartbeat.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          clientId_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return MessageProto.internal_static_Message_Heartbeat_descriptor;
        }

        @java.lang.Override
        public MessageProto.Message.Heartbeat getDefaultInstanceForType() {
          return MessageProto.Message.Heartbeat.getDefaultInstance();
        }

        @java.lang.Override
        public MessageProto.Message.Heartbeat build() {
          MessageProto.Message.Heartbeat result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public MessageProto.Message.Heartbeat buildPartial() {
          MessageProto.Message.Heartbeat result = new MessageProto.Message.Heartbeat(this);
          result.clientId_ = clientId_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof MessageProto.Message.Heartbeat) {
            return mergeFrom((MessageProto.Message.Heartbeat)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(MessageProto.Message.Heartbeat other) {
          if (other == MessageProto.Message.Heartbeat.getDefaultInstance()) return this;
          if (!other.getClientId().isEmpty()) {
            clientId_ = other.clientId_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          MessageProto.Message.Heartbeat parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (MessageProto.Message.Heartbeat) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object clientId_ = "";
        /**
         * <pre>
         * 客户端id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return The clientId.
         */
        public java.lang.String getClientId() {
          java.lang.Object ref = clientId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * 客户端id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return The bytes for clientId.
         */
        public com.google.protobuf.ByteString
            getClientIdBytes() {
          java.lang.Object ref = clientId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            clientId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 客户端id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @param value The clientId to set.
         * @return This builder for chaining.
         */
        public Builder setClientId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          clientId_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 客户端id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearClientId() {
          
          clientId_ = getDefaultInstance().getClientId();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 客户端id
         * </pre>
         *
         * <code>string clientId = 1;</code>
         * @param value The bytes for clientId to set.
         * @return This builder for chaining.
         */
        public Builder setClientIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          clientId_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Message.Heartbeat)
      }

      // @@protoc_insertion_point(class_scope:Message.Heartbeat)
      private static final MessageProto.Message.Heartbeat DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new MessageProto.Message.Heartbeat();
      }

      public static MessageProto.Message.Heartbeat getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Heartbeat>
          PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
        @java.lang.Override
        public Heartbeat parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Heartbeat(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Heartbeat> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Heartbeat> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public MessageProto.Message.Heartbeat getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      AUTHENTICATION(2),
      HEARTBEAT(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return AUTHENTICATION;
          case 3: return HEARTBEAT;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.Message.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <pre>
     * 消息类型
     * </pre>
     *
     * <code>.Message.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override public MessageProto.Message.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageProto.Message.MessageType result = MessageProto.Message.MessageType.valueOf(messageType_);
      return result == null ? MessageProto.Message.MessageType.UNRECOGNIZED : result;
    }

    public static final int AUTHENTICATION_FIELD_NUMBER = 2;
    /**
     * <code>.Message.Authentication authentication = 2;</code>
     * @return Whether the authentication field is set.
     */
    @java.lang.Override
    public boolean hasAuthentication() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Message.Authentication authentication = 2;</code>
     * @return The authentication.
     */
    @java.lang.Override
    public MessageProto.Message.Authentication getAuthentication() {
      if (dataBodyCase_ == 2) {
         return (MessageProto.Message.Authentication) dataBody_;
      }
      return MessageProto.Message.Authentication.getDefaultInstance();
    }
    /**
     * <code>.Message.Authentication authentication = 2;</code>
     */
    @java.lang.Override
    public MessageProto.Message.AuthenticationOrBuilder getAuthenticationOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (MessageProto.Message.Authentication) dataBody_;
      }
      return MessageProto.Message.Authentication.getDefaultInstance();
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 3;
    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public MessageProto.Message.Heartbeat getHeartbeat() {
      if (dataBodyCase_ == 3) {
         return (MessageProto.Message.Heartbeat) dataBody_;
      }
      return MessageProto.Message.Heartbeat.getDefaultInstance();
    }
    /**
     * <code>.Message.Heartbeat heartbeat = 3;</code>
     */
    @java.lang.Override
    public MessageProto.Message.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (MessageProto.Message.Heartbeat) dataBody_;
      }
      return MessageProto.Message.Heartbeat.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageType_ != MessageProto.Message.MessageType.AUTHENTICATION.getNumber()) {
        output.writeEnum(1, messageType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (MessageProto.Message.Authentication) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (MessageProto.Message.Heartbeat) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageType_ != MessageProto.Message.MessageType.AUTHENTICATION.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (MessageProto.Message.Authentication) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (MessageProto.Message.Heartbeat) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageProto.Message)) {
        return super.equals(obj);
      }
      MessageProto.Message other = (MessageProto.Message) obj;

      if (messageType_ != other.messageType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getAuthentication()
              .equals(other.getAuthentication())) return false;
          break;
        case 3:
          if (!getHeartbeat()
              .equals(other.getHeartbeat())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + AUTHENTICATION_FIELD_NUMBER;
          hash = (53 * hash) + getAuthentication().hashCode();
          break;
        case 3:
          hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
          hash = (53 * hash) + getHeartbeat().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageProto.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProto.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProto.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageProto.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageProto.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageProto.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Message)
        MessageProto.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProto.Message.class, MessageProto.Message.Builder.class);
      }

      // Construct using MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        messageType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_Message_descriptor;
      }

      @java.lang.Override
      public MessageProto.Message getDefaultInstanceForType() {
        return MessageProto.Message.getDefaultInstance();
      }

      @java.lang.Override
      public MessageProto.Message build() {
        MessageProto.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public MessageProto.Message buildPartial() {
        MessageProto.Message result = new MessageProto.Message(this);
        result.messageType_ = messageType_;
        if (dataBodyCase_ == 2) {
          if (authenticationBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = authenticationBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (heartbeatBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = heartbeatBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProto.Message) {
          return mergeFrom((MessageProto.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProto.Message other) {
        if (other == MessageProto.Message.getDefaultInstance()) return this;
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case AUTHENTICATION: {
            mergeAuthentication(other.getAuthentication());
            break;
          }
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProto.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProto.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int messageType_ = 0;
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.Message.MessageType messageType = 1;</code>
       * @return The enum numeric value on the wire for messageType.
       */
      @java.lang.Override public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.Message.MessageType messageType = 1;</code>
       * @param value The enum numeric value on the wire for messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageTypeValue(int value) {
        
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.Message.MessageType messageType = 1;</code>
       * @return The messageType.
       */
      @java.lang.Override
      public MessageProto.Message.MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageProto.Message.MessageType result = MessageProto.Message.MessageType.valueOf(messageType_);
        return result == null ? MessageProto.Message.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.Message.MessageType messageType = 1;</code>
       * @param value The messageType to set.
       * @return This builder for chaining.
       */
      public Builder setMessageType(MessageProto.Message.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息类型
       * </pre>
       *
       * <code>.Message.MessageType messageType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          MessageProto.Message.Authentication, MessageProto.Message.Authentication.Builder, MessageProto.Message.AuthenticationOrBuilder> authenticationBuilder_;
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       * @return Whether the authentication field is set.
       */
      @java.lang.Override
      public boolean hasAuthentication() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       * @return The authentication.
       */
      @java.lang.Override
      public MessageProto.Message.Authentication getAuthentication() {
        if (authenticationBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (MessageProto.Message.Authentication) dataBody_;
          }
          return MessageProto.Message.Authentication.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return authenticationBuilder_.getMessage();
          }
          return MessageProto.Message.Authentication.getDefaultInstance();
        }
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      public Builder setAuthentication(MessageProto.Message.Authentication value) {
        if (authenticationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          authenticationBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      public Builder setAuthentication(
          MessageProto.Message.Authentication.Builder builderForValue) {
        if (authenticationBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          authenticationBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      public Builder mergeAuthentication(MessageProto.Message.Authentication value) {
        if (authenticationBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != MessageProto.Message.Authentication.getDefaultInstance()) {
            dataBody_ = MessageProto.Message.Authentication.newBuilder((MessageProto.Message.Authentication) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            authenticationBuilder_.mergeFrom(value);
          } else {
            authenticationBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      public Builder clearAuthentication() {
        if (authenticationBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          authenticationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      public MessageProto.Message.Authentication.Builder getAuthenticationBuilder() {
        return getAuthenticationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      @java.lang.Override
      public MessageProto.Message.AuthenticationOrBuilder getAuthenticationOrBuilder() {
        if ((dataBodyCase_ == 2) && (authenticationBuilder_ != null)) {
          return authenticationBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (MessageProto.Message.Authentication) dataBody_;
          }
          return MessageProto.Message.Authentication.getDefaultInstance();
        }
      }
      /**
       * <code>.Message.Authentication authentication = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageProto.Message.Authentication, MessageProto.Message.Authentication.Builder, MessageProto.Message.AuthenticationOrBuilder> 
          getAuthenticationFieldBuilder() {
        if (authenticationBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = MessageProto.Message.Authentication.getDefaultInstance();
          }
          authenticationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MessageProto.Message.Authentication, MessageProto.Message.Authentication.Builder, MessageProto.Message.AuthenticationOrBuilder>(
                  (MessageProto.Message.Authentication) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return authenticationBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          MessageProto.Message.Heartbeat, MessageProto.Message.Heartbeat.Builder, MessageProto.Message.HeartbeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       * @return Whether the heartbeat field is set.
       */
      @java.lang.Override
      public boolean hasHeartbeat() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       * @return The heartbeat.
       */
      @java.lang.Override
      public MessageProto.Message.Heartbeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (MessageProto.Message.Heartbeat) dataBody_;
          }
          return MessageProto.Message.Heartbeat.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return heartbeatBuilder_.getMessage();
          }
          return MessageProto.Message.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      public Builder setHeartbeat(MessageProto.Message.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      public Builder setHeartbeat(
          MessageProto.Message.Heartbeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      public Builder mergeHeartbeat(MessageProto.Message.Heartbeat value) {
        if (heartbeatBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != MessageProto.Message.Heartbeat.getDefaultInstance()) {
            dataBody_ = MessageProto.Message.Heartbeat.newBuilder((MessageProto.Message.Heartbeat) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            heartbeatBuilder_.mergeFrom(value);
          } else {
            heartbeatBuilder_.setMessage(value);
          }
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      public MessageProto.Message.Heartbeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      @java.lang.Override
      public MessageProto.Message.HeartbeatOrBuilder getHeartbeatOrBuilder() {
        if ((dataBodyCase_ == 3) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (MessageProto.Message.Heartbeat) dataBody_;
          }
          return MessageProto.Message.Heartbeat.getDefaultInstance();
        }
      }
      /**
       * <code>.Message.Heartbeat heartbeat = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          MessageProto.Message.Heartbeat, MessageProto.Message.Heartbeat.Builder, MessageProto.Message.HeartbeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = MessageProto.Message.Heartbeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              MessageProto.Message.Heartbeat, MessageProto.Message.Heartbeat.Builder, MessageProto.Message.HeartbeatOrBuilder>(
                  (MessageProto.Message.Heartbeat) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return heartbeatBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Message)
    }

    // @@protoc_insertion_point(class_scope:Message)
    private static final MessageProto.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageProto.Message();
    }

    public static MessageProto.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      @java.lang.Override
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public MessageProto.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Authentication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Authentication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_Heartbeat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Message_Heartbeat_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MessageProto.proto\"\274\002\n\007Message\022)\n\013mess" +
      "ageType\030\001 \001(\0162\024.Message.MessageType\0221\n\016a" +
      "uthentication\030\002 \001(\0132\027.Message.Authentica" +
      "tionH\000\022\'\n\theartbeat\030\003 \001(\0132\022.Message.Hear" +
      "tbeatH\000\032M\n\016Authentication\022\020\n\010clientId\030\001 " +
      "\001(\t\022\025\n\rclientAddress\030\002 \001(\t\022\022\n\nclientName" +
      "\030\003 \001(\t\032\035\n\tHeartbeat\022\020\n\010clientId\030\001 \001(\t\"0\n" +
      "\013MessageType\022\022\n\016AUTHENTICATION\020\000\022\r\n\tHEAR" +
      "TBEAT\020\001B\n\n\010dataBodyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_descriptor,
        new java.lang.String[] { "MessageType", "Authentication", "Heartbeat", "DataBody", });
    internal_static_Message_Authentication_descriptor =
      internal_static_Message_descriptor.getNestedTypes().get(0);
    internal_static_Message_Authentication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Authentication_descriptor,
        new java.lang.String[] { "ClientId", "ClientAddress", "ClientName", });
    internal_static_Message_Heartbeat_descriptor =
      internal_static_Message_descriptor.getNestedTypes().get(1);
    internal_static_Message_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Message_Heartbeat_descriptor,
        new java.lang.String[] { "ClientId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
